### ISSUE TITLE
Issue with plugin at Sonar-10.4  java.lang.ClassNotFoundException: org.sonar.plugins.java.api.CheckRegistrar

### ISSUE THREAD

**Issue by C4tWithShell** [QualInsight/qualinsight-plugins-sonarqube-smell#66]
```
09:58:41  java.lang.NoClassDefFoundError: org/sonar/plugins/java/api/CheckRegistrar
09:58:41  	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
09:58:41  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
09:58:41  	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
09:58:41  	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
09:58:41  	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
09:58:41  	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
09:58:41  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
09:58:41  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
09:58:41  	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:135)
09:58:41  	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
09:58:41  	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:97)
09:58:41  	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:86)
09:58:41  	at com.qualinsight.plugins.sonarqube.smell.plugin.SmellPlugin.define(SmellPlugin.java:59)
09:58:41  	at org.sonar.scanner.bootstrap.ExtensionInstaller.installExtensionsForPlugins(ExtensionInstaller.java:64)
09:58:41  	at org.sonar.scanner.bootstrap.ExtensionInstaller.install(ExtensionInstaller.java:51)
09:58:41  	at org.sonar.scanner.bootstrap.SpringScannerContainer.addScannerExtensions(SpringScannerContainer.java:175)
09:58:41  	at org.sonar.scanner.bootstrap.SpringScannerContainer.doBeforeStart(SpringScannerContainer.java:155)
09:58:41  	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:221)
09:58:41  	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:202)
09:58:41  	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:138)
09:58:41  	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:223)
09:58:41  	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:202)
09:58:41  	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:71)
09:58:41  	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:65)
09:58:41  	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
09:58:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:58:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
09:58:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:58:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
09:58:41  	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
09:58:41  	at jdk.proxy1/jdk.proxy1.$Proxy0.execute(Unknown Source)
09:58:41  	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
09:58:41  	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
09:58:41  	at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
09:58:41  	at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
09:58:41  	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
09:58:41  Caused by: java.lang.ClassNotFoundException: org.sonar.plugins.java.api.CheckRegistrar
09:58:41  	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
09:58:41  	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:97)
09:58:41  	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:86)
09:58:41  	... 36 more
```

**Comment by bobesz** [comment]
https://community.sonarsource.com/t/caused-by-java-lang-classnotfoundexception-org-sonar-plugins-java-api-checkregistrar/114115

**Comment by suvl** [comment]
We shall consider this plugin dead. No fix since march.
